name: Aprende expresiones
run-name: pipeline de expresiones

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: 'usuario'
        required: true
        default: 'beto'
        type: string

jobs:
 expresiones:
   if: ${{inputs.nombre == 'beto'}}
   runs-on: ubuntu-latest
   steps:
     - name: imprimir
       run: echo beto

        
