name: Aprende expresiones
run-name: pipeline de expresiones

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: 'usuario'
        required: true
        default: 'beto'
        type: string

env:
  GLOBAL_VAR: "Este valor está en todo el workflow"

jobs:
  expresiones:
    if: ${{ github.event.inputs.nombre == 'beto' }}
    runs-on: ubuntu-latest
    steps:
      - name: imprimir
        run: echo "beto"

  variable_global:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar solo si GLOBAL_VAR != HOLA
        if: ${{ env.GLOBAL_VAR != 'HOLA' }}
        run: echo $GLOBAL_VAR
