name: variable
run-name: reto-variable

on: 
  workflow_dispatch:
    inputs:
        edad:
          description: 'edades'
          required: true
          default: '28'
          type: string

jobs:
  contextos:
    if: ${{ inputs.edad < 15 }}
    runs-on: ubuntu-latest
    env:
        VARIABLE_ENV: 'variabel global'
        MASCO: ${{vars.MASCOTA}}
    steps:
        - name: 'valor github'
          run: echo "${{github.actor}} corre"
        - name: 'nuevo variable'
          run: echo $VARIABLE_ENV && echo $MASCO
    

